# -*- coding: utf-8 -*-
"""
/***************************************************************************
 embedded_svg
                                 A QGIS plugin
 embedding SVG into Projectfiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-09
        copyright            : (C) 2020 by d.b.g. Datenbankgesellschaft
        email                : info@datenbankgesellschaft.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load embedded_svg class from file embedded_svg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .svg_embedder import embedded_svg
    return embedded_svg(iface)
